USE [master]
GO
/****** Object:  Database [iara]    Script Date: 1/20/2026 11:24:18 AM ******/
CREATE DATABASE [iara]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iara', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\iara.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'iara_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\iara_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [iara] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iara].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [iara] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [iara] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [iara] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [iara] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [iara] SET ARITHABORT OFF 
GO
ALTER DATABASE [iara] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [iara] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [iara] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [iara] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [iara] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [iara] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [iara] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [iara] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [iara] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [iara] SET  ENABLE_BROKER 
GO
ALTER DATABASE [iara] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [iara] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [iara] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [iara] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [iara] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [iara] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [iara] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [iara] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [iara] SET  MULTI_USER 
GO
ALTER DATABASE [iara] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [iara] SET DB_CHAINING OFF 
GO
ALTER DATABASE [iara] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [iara] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [iara] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [iara] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [iara] SET QUERY_STORE = OFF
GO
USE [iara]
GO
/****** Object:  Table [dbo].[CATCH_QUOTAS]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATCH_QUOTAS](
	[quota_id] [int] IDENTITY(1,1) NOT NULL,
	[permit_id] [int] NOT NULL,
	[species_id] [int] NOT NULL,
	[year] [smallint] NOT NULL,
	[min_catch_kg] [decimal](12, 2) NULL,
	[avg_catch_kg] [decimal](12, 2) NULL,
	[max_catch_kg] [decimal](12, 2) NOT NULL,
	[fuel_hours_limit] [int] NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[quota_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CATCH_QUOTAS_PermitSpeciesYear] UNIQUE NONCLUSTERED 
(
	[permit_id] ASC,
	[species_id] ASC,
	[year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTIONS]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTIONS](
	[inspection_id] [int] IDENTITY(1,1) NOT NULL,
	[vessel_id] [int] NOT NULL,
	[inspector_id] [int] NOT NULL,
	[inspection_date] [datetime2](7) NOT NULL,
	[is_legal] [bit] NULL,
	[notes] [nvarchar](max) NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[inspection_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGBOOK]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGBOOK](
	[log_entry_id] [int] IDENTITY(1,1) NOT NULL,
	[vessel_id] [int] NOT NULL,
	[captain_id] [int] NOT NULL,
	[start_time] [datetime2](7) NOT NULL,
	[duration_hours] [int] NULL,
	[latitude] [decimal](9, 6) NULL,
	[longitude] [decimal](9, 6) NULL,
	[species_id] [int] NOT NULL,
	[catch_kg] [decimal](10, 2) NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[log_entry_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMITS]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMITS](
	[permit_id] [int] IDENTITY(1,1) NOT NULL,
	[vessel_id] [int] NOT NULL,
	[issue_date] [date] NOT NULL,
	[expiry_date] [date] NOT NULL,
	[is_active] [bit] NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[permit_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONNEL]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONNEL](
	[person_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](100) NOT NULL,
	[role] [nvarchar](50) NOT NULL,
	[contact_email] [nvarchar](100) NULL,
	[password_hash] [nvarchar](256) NULL,
	[is_active] [bit] NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[person_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SPECIES]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SPECIES](
	[species_id] [int] IDENTITY(1,1) NOT NULL,
	[species_name] [nvarchar](100) NOT NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[species_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[species_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TICKETS]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TICKETS](
	[ticket_id] [int] IDENTITY(1,1) NOT NULL,
	[ticket_number] [nvarchar](50) NOT NULL,
	[inspection_id] [int] NOT NULL,
	[penalty_amount] [decimal](10, 2) NULL,
	[is_validated] [bit] NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[ticket_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ticket_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VESSELS]    Script Date: 1/20/2026 11:24:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VESSELS](
	[vessel_id] [int] IDENTITY(1,1) NOT NULL,
	[reg_number] [nvarchar](50) NOT NULL,
	[vessel_name] [nvarchar](100) NOT NULL,
	[captain_id] [int] NULL,
	[owner_details] [nvarchar](500) NULL,
	[tonnage] [decimal](10, 2) NULL,
	[length_m] [decimal](8, 2) NULL,
	[width_m] [decimal](8, 2) NULL,
	[engine_power_kw] [decimal](10, 2) NULL,
	[fuel_type] [nvarchar](50) NULL,
	[displacement_tons] [decimal](10, 2) NULL,
	[created_at] [datetime2](7) NULL,
	[updated_at] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[vessel_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[reg_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATCH_QUOTAS] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[INSPECTIONS] ADD  DEFAULT ((1)) FOR [is_legal]
GO
ALTER TABLE [dbo].[INSPECTIONS] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[LOGBOOK] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[PERMITS] ADD  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[PERMITS] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[PERSONNEL] ADD  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[PERSONNEL] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[SPECIES] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[TICKETS] ADD  DEFAULT ((0)) FOR [is_validated]
GO
ALTER TABLE [dbo].[TICKETS] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[VESSELS] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[CATCH_QUOTAS]  WITH CHECK ADD  CONSTRAINT [FK_CATCH_QUOTAS_Permit] FOREIGN KEY([permit_id])
REFERENCES [dbo].[PERMITS] ([permit_id])
GO
ALTER TABLE [dbo].[CATCH_QUOTAS] CHECK CONSTRAINT [FK_CATCH_QUOTAS_Permit]
GO
ALTER TABLE [dbo].[CATCH_QUOTAS]  WITH CHECK ADD  CONSTRAINT [FK_CATCH_QUOTAS_Species] FOREIGN KEY([species_id])
REFERENCES [dbo].[SPECIES] ([species_id])
GO
ALTER TABLE [dbo].[CATCH_QUOTAS] CHECK CONSTRAINT [FK_CATCH_QUOTAS_Species]
GO
ALTER TABLE [dbo].[INSPECTIONS]  WITH CHECK ADD  CONSTRAINT [FK_INSPECTIONS_Inspector] FOREIGN KEY([inspector_id])
REFERENCES [dbo].[PERSONNEL] ([person_id])
GO
ALTER TABLE [dbo].[INSPECTIONS] CHECK CONSTRAINT [FK_INSPECTIONS_Inspector]
GO
ALTER TABLE [dbo].[INSPECTIONS]  WITH CHECK ADD  CONSTRAINT [FK_INSPECTIONS_Vessel] FOREIGN KEY([vessel_id])
REFERENCES [dbo].[VESSELS] ([vessel_id])
GO
ALTER TABLE [dbo].[INSPECTIONS] CHECK CONSTRAINT [FK_INSPECTIONS_Vessel]
GO
ALTER TABLE [dbo].[LOGBOOK]  WITH CHECK ADD  CONSTRAINT [FK_LOGBOOK_Captain] FOREIGN KEY([captain_id])
REFERENCES [dbo].[PERSONNEL] ([person_id])
GO
ALTER TABLE [dbo].[LOGBOOK] CHECK CONSTRAINT [FK_LOGBOOK_Captain]
GO
ALTER TABLE [dbo].[LOGBOOK]  WITH CHECK ADD  CONSTRAINT [FK_LOGBOOK_Species] FOREIGN KEY([species_id])
REFERENCES [dbo].[SPECIES] ([species_id])
GO
ALTER TABLE [dbo].[LOGBOOK] CHECK CONSTRAINT [FK_LOGBOOK_Species]
GO
ALTER TABLE [dbo].[LOGBOOK]  WITH CHECK ADD  CONSTRAINT [FK_LOGBOOK_Vessel] FOREIGN KEY([vessel_id])
REFERENCES [dbo].[VESSELS] ([vessel_id])
GO
ALTER TABLE [dbo].[LOGBOOK] CHECK CONSTRAINT [FK_LOGBOOK_Vessel]
GO
ALTER TABLE [dbo].[PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_PERMITS_Vessel] FOREIGN KEY([vessel_id])
REFERENCES [dbo].[VESSELS] ([vessel_id])
GO
ALTER TABLE [dbo].[PERMITS] CHECK CONSTRAINT [FK_PERMITS_Vessel]
GO
ALTER TABLE [dbo].[TICKETS]  WITH CHECK ADD  CONSTRAINT [FK_TICKETS_Inspection] FOREIGN KEY([inspection_id])
REFERENCES [dbo].[INSPECTIONS] ([inspection_id])
GO
ALTER TABLE [dbo].[TICKETS] CHECK CONSTRAINT [FK_TICKETS_Inspection]
GO
ALTER TABLE [dbo].[VESSELS]  WITH CHECK ADD  CONSTRAINT [FK_VESSELS_Captain] FOREIGN KEY([captain_id])
REFERENCES [dbo].[PERSONNEL] ([person_id])
GO
ALTER TABLE [dbo].[VESSELS] CHECK CONSTRAINT [FK_VESSELS_Captain]
GO
USE [master]
GO
ALTER DATABASE [iara] SET  READ_WRITE 
GO
